### ISSUE TITLE
Fails to build with 4.9 & musl libc

### ISSUE THREAD

**Issue by jku** [paulusmack/ppp#73]
pppol2tp plugin fails to build with linux 4.9 headers and musl libc with:

```
| In file included from pppol2tp.c:34:0:
| /usr/include/linux/if.h:97:2: error: expected identifier before numeric constant
|   IFF_LOWER_UP   = 1<<16, /* __volatile__ */
```

I've fixed this locally by removing `#include <linux/if_pppox.h>` from openl2tp.c and pppol2tp.c as the include isn't actually needed, but I'm unsure whether this is the fix you'd like upstream... Let me know if you'd rather have a PR.

**Comment by Neustradamus** [comment]
@jku: The problem is always here in mainline and up-to-date linux kernel?

**Comment by jku** [comment]
Sorry, I wouldn't know: I've not compiled anything for musl in a few years.

**Comment by Neustradamus** [comment]
@jku: Ok :/

**Comment by RICCIARDI-Adrien** [comment]
Hi,
This issue might be closed now that musl support has been merged (see 7555728).

**Comment by Neustradamus** [comment]
@RICCIARDI-Adrien: Have you tested, perfect for your?

**Comment by Neustradamus** [comment]
@RICCIARDI-Adrien: Have you tested, perfect for you?

**Comment by Neustradamus** [comment]
@yegorich, @mjeveritt, @Polynomial-C, @RICCIARDI-Adrien, @jku: Have you tested, perfect for you?

Linked to:
- https://github.com/paulusmack/ppp/issues/51
- https://github.com/paulusmack/ppp/pull/110
- https://github.com/paulusmack/ppp/commit/7555728c50db87ae7d5b8c018c006a14bf374584

**Comment by mjeveritt** [comment]
> @mjeveritt: Have you tested, perfect for you?
> 
> Linked to:
> 
>     * #51
>     * #110
>     * [7555728](https://github.com/paulusmack/ppp/commit/7555728c50db87ae7d5b8c018c006a14bf374584)

I can't speak to #51 at this stage, but the other two are definitely covered in Gentoo musl's patch [here](https://gitweb.gentoo.org/proj/musl.git/tree/net-dialup/ppp/files/ppp-2.4.7-musl.patch) .

Tangentially I'm helping with #111 so that we can eliminate many of the Gentoo 'glibc'/vanilla patches for ppp, since we were looking to merge musl support into the main ::gentoo repository anyway. This will be a good tidy-up for the distro :smile: .
